[package]
name = "roasted"
version = "0.1.0"
authors = ["Julien ROLLIN <julien.rollin.tech@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
chrono = "0.4"
uuid = { version = "0.8", features = [ "v4"] }
